### ISSUE TITLE
CLI not recognizing config file from stdin

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#15]
This used to work, but now it does not seem to work anymore with v0.2:

```
~/repos/precice/tutorials/flow-over-heated-plate-two-meshes [develop_su2pywrapper]$ cat precice-config.xml | precice-config-visualizer | dot -Tpng > config.png
usage: precice-config-visualizer [-h] [-o [OUTFILE]]
                                 [--data-access {full,merged,hide}]
                                 [--data-exchange {full,merged,hide}]
                                 [--communicators {full,merged,hide}]
                                 [--cplschemes {full,merged,hide}]
                                 [--no-watchpoints] [--no-colors]
                                 infile
precice-config-visualizer: error: the following arguments are required: infile
```

The GUI works.

I have not bisected yet, @fsimonis let me know if you need me to.

**Comment by fsimonis** [comment]
This is indeed is a change that I didn't notice during the modularization of the core functionality.

I can fix this, but the question is if the use-case of reading from stdin is actually relevant.
After all, preCICE configs are not intermediate objects. They always need to exist for preCICE to use them.

Work-wise, both decisions result in equal amount of work:

- Readding the feature requires implementation changes and a new release.
- Not adding the feature requires documentations changes in various places.

**Comment by MakisH** [comment]
Is these any other way to use the CLI? Because we currently provide that in the VM, teach it in the training course, and I have some scripting ideas in mind.

A new release is fine. This is a regression.

**Comment by MakisH** [comment]
We just realized we were emphasizing different aspects. What is broken is specifically the stdin piping into the config-visualizer. But the following is also possible:

```shell
precice-config-visualizer precice-config.xml | dot -Tpdf > config.pdf
```

We should just [document this](https://precice.org/tooling-config-visualization.html) and just remove the alternative way. No reason to invest extra effort.

Edit: It is actually documented, but not in the "using the CLI". This part probably needs some restructuring.

**Comment by fsimonis** [comment]
The `<stdin>` use-case was removed form the [precice.org/tooling-config-visualization](https://precice.org/tooling-config-visualization.html#general-usage) and the Readme.

I'll close this as "not planned".
