### ISSUE TITLE
Building complaining about failing to build dependencies

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#16]
```
~$ pipx install precice-config-visualizer
Fatal error from pip prevented installation. Full pip output in file:
    /home/gc/.local/pipx/logs/cmd_2024-03-23_22.29.30_pip_errors.log

pip seemed to fail to build package:
    pycairo

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    Package cairo was not found in the pkg-config search path.

Error installing precice-config-visualizer.
```

Same when I try to install directly from the repository:

```
~/repos/precice/config-visualizer [master]$ pipx install https://github.com/precice/config-visualizer/archive/master.zip
Fatal error from pip prevented installation. Full pip output in file:
    /home/gc/.local/pipx/logs/cmd_2024-03-23_22.19.38_pip_errors.log

pip seemed to fail to build package:
    pycairo

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    Package cairo was not found in the pkg-config search path.

Error installing precice-config-visualizer from spec 'https://github.com/precice/config-visualizer/archive/master.zip'.
```

**Comment by fsimonis** [comment]
`pygobject` (GNOME project) has `pycairo` as a dependency, which requires `libcairo2-dev`.

Installing `python3-cairo` via apt provides the dependency, installing it via venv doesn't.

Short-term solution: `libcairo2-dev`
Long-term solution: flatpak :sweat_smile:

**Comment by MakisH** [comment]
Installing `libcairo2-dev` helped change the error message:

```
~$ pipx install https://github.com/precice/config-visualizer/archive/master.zip
Fatal error from pip prevented installation. Full pip output in file:
    /home/gc/.local/pipx/logs/cmd_2024-03-26_10.13.05_pip_errors.log

pip seemed to fail to build package:
    PyGObject

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../meson.build:29:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found.
    error: metadata-generation-failed

Error installing precice-config-visualizer from spec 'https://github.com/precice/config-visualizer/archive/master.zip'.
```

In any case, something looks wrong. Let's find which packages we need, and document. A flatpak/snap would be nice for such a stand-alone tool anyway.

**Comment by fsimonis** [comment]
I just recalled that I ran into the same issue recently on a new Ubuntu install.

[The official docs state](https://gnome.pages.gitlab.gnome.org/pygobject/getting_started.html#ubuntu-getting-started) to install the necessary packages via apt.

Either directly the package:
```
sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-4.0
```

Or the dependencies for pip installations:
```
sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0 to
```

Can you try that?

**Comment by MakisH** [comment]
I needed to install `gobject-introspection libgirepository1.0-dev` and the previously mentioned `libcairo2-dev` in my case, and it worked :tada:.

Can we somehow define or at least document these dependencies here?

(FYI, the CLI still has the same issue #15)

**Comment by MakisH** [comment]
Closed for me by installing the right dependencies. The documentation in https://github.com/precice/precice.github.io/pull/363 covers everything I needed.
