### ISSUE TITLE
Building complaining about non-existing directory

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#17]
I was in my local copy of the repository when I triggered the installation via the repository URL, and I got a strange error, mentioning an incomplete path:

```diff
- /home/gc/repos/precice/config-visualizer
+ /home/gc/repos/config-visualizer
```

Log:

```
~/repos/precice/config-visualizer [master]$ pip3 install --user https://github.com/precice/config-visualizer/archive/master.zip
Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
Collecting https://github.com/precice/config-visualizer/archive/master.zip
  Using cached https://github.com/precice/config-visualizer/archive/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from precice-config-visualizer==0.0.1) (4.8.0)
Requirement already satisfied: pydot in /home/gc/.local/lib/python3.10/site-packages (from precice-config-visualizer==0.0.1) (1.4.2)
Requirement already satisfied: xdot in /home/gc/.local/lib/python3.10/site-packages (from precice-config-visualizer==0.0.1) (1.3)
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from precice-config-visualizer==0.0.1) (3.42.1)
Requirement already satisfied: pyparsing>=2.1.4 in /usr/lib/python3/dist-packages (from pydot->precice-config-visualizer==0.0.1) (2.4.7)
Requirement already satisfied: pycairo>=1.16.0 in /usr/lib/python3/dist-packages (from PyGObject->precice-config-visualizer==0.0.1) (1.20.1)
Requirement already satisfied: numpy in /home/gc/.local/lib/python3.10/site-packages (from xdot->precice-config-visualizer==0.0.1) (1.26.4)
Building wheels for collected packages: precice-config-visualizer
  Building wheel for precice-config-visualizer (pyproject.toml) ... done
  Created wheel for precice-config-visualizer: filename=precice_config_visualizer-0.0.1-py3-none-any.whl size=27131 sha256=3f438168172e8a5be7e336a27d1f21fc7d58fd334f4366dd9076d7dc721daee1
  Stored in directory: /tmp/pip-ephem-wheel-cache-kngzp93h/wheels/a1/6a/12/7f9e71d639013095d5a28438e33b043e772c71746b71860d22
Successfully built precice-config-visualizer
DEPRECATION: flatbuffers 1.12.1-git20200711.33e2d80-dfsg1-0.6 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of flatbuffers or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: precice-config-visualizer
  Attempting uninstall: precice-config-visualizer
    Found existing installation: precice-config-visualizer 0.2.0
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/gc/repos/config-visualizer'
```

**Comment by fsimonis** [comment]
This looks very similar to an issue I ran into with @IshaanDesai during the micro-manager port to `pyproject.toml`. Pip gets confused when it tries to install a package, which is already present in the local directory.

Can you try installing it from another directory?

Is it possible that the ghost repo `/home/gc/repos/config-visualizer` existed at some point and that you installed the config-visualizer from there.

Also, pipx and venv :wink:

**Comment by IshaanDesai** [comment]
> I was in my local copy of the repository when I triggered the installation via the repository URL

So from within the repository folder you ran `pip install <url>`? I would generally not do this in any case as it definitely confuses pip because you have a local setup file lying around, while at the same time you ask pip to pull from a remote repository. The config-visualizer is now on PyPI: https://pypi.org/project/precice-config-visualizer/ so you could also just install by name.

**Comment by MakisH** [comment]
> Can you try installing it from another directory?

I suppose this works, but currently I am facing a different issue #16.

> Is it possible that the ghost repo /home/gc/repos/config-visualizer existed at some point and that you installed the config-visualizer from there.

No, I don't think this was ever the case. The correct repository existed, yes. The ghost one, no.

> Also, pipx and ven

Potato, potato, same issue :sweat_smile: 

> I would generally not do this in any case as it definitely confuses pip because you have a local setup file lying around, while at the same time you ask pip to pull from a remote repository.

Clearly, there is an issue. But I don't think this is user error, this should just not happen and the directory should be irrelevant as long as there is a URL. But it is enough for me to know this is an issue with PIP and not with this package. I just wanted to raise a flag early enough (I prefer early false alarms than late crisis handling).

> The config-visualizer is now on PyPI: https://pypi.org/project/precice-config-visualizer/ so you could also just install by name.

Still leads to #16.

**Comment by fsimonis** [comment]
> Potato, potato, same issue 😅

Really? Then there is a bug somewhere. pipx/venv install in isolation, independent of the local directory and existing packages.

**Comment by MakisH** [comment]
Now that I have all dependencies installed, I actually tried both with `pipx` and `pip3 --user` and I cannot reproduce the issue anymore. I guess this has nothing to do with this project, let's not worry any further here.
