### ISSUE TITLE
Picture resolution not matching canvas resolution for generated pictures

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#19]
For example, the `flow-over-heated-plate` gives a larger canvas than the picture itself:

![graph](https://github.com/precice/config-visualizer/assets/4943683/c790aa27-b595-49da-be00-a9b63b7712fe)

This is actually the same for PDF and SVG.

This was not the case in v0.1.

```
$ apt-cache show libcairo2-dev
Package: libcairo2-dev
Architecture: amd64
Version: 1.16.0-5ubuntu2
```

**Comment by fsimonis** [comment]
Interesting. Are you using the cli + dot to generate the output or are you exporting via the GUI?

**Comment by MakisH** [comment]
Just the CLI. If I use the PNG, I get the correct canvas size, but still a bit low resolution:

![precice-config](https://github.com/precice/config-visualizer/assets/4943683/5b5543e9-a57f-49ca-80ec-e7047027d7b5)

**Comment by fsimonis** [comment]
> Just the CLI.

The CLI outputs dot :wink: 

Can you list the full commands?

**Comment by MakisH** [comment]
I am using the default documented way:

```shell
precice-config-visualizer precice-config.xml | dot -Tpng > precice-config.png
```

**Comment by fsimonis** [comment]
Traced it back to the margin property. I set its default in the CLI to 0 and pushed a bugfix release v0.2.1.

**Comment by MakisH** [comment]
Worked now, thanks!
