### ISSUE TITLE
Mention pip install from github 

### ISSUE THREAD

**Issue by fsimonis** [precice/config-visualizer#2]
This tool can be installed straight from github using
```
pip3 install --user git+https://github.com/precice/config-visualizer.git
```

We should add this to the Readme and wiki

---

Or as a local repository via:
```
$ git clone https://github.com/precice/config-visualizer.git
$ python3 -m pip install --user --editable config-visualizer
```

**Comment by MakisH** [comment]
But does this require that a user already has Git installed? Or does pip install Git through pip in that case? *(pipception)*

**Comment by fsimonis** [comment]
The above version does indeed require `git`.
So, I added the installation via the archive zip to the README. This does not require `git`.
