### ISSUE TITLE
Support for configs with direct mesh access

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#22]
Trying to visualize the `flow-over-heated-plate-direct` case config, I get:

```
~/repos/precice/tutorials/partitioned-heat-conduction-direct [add-config-visualizations]$ preciceToPNG 
dot: compound.c:369: makeCompoundEdge: Assertion `bez->sflag' failed.
Aborted (core dumped)
```

I understand that the mapping arrows cannot currently be drawn from a mesh that is not used.

I guess this is an enhancement rather than a bug, and I have kept a placeholder for that tutorial in https://github.com/precice/tutorials/pull/514.

**Comment by fsimonis** [comment]
This is a bug in dot/graphviz which is shipped with Ubuntu 22.04 LTS and the current Ubuntu 24.04 LTS, which is `graphviz version 2.43.0` on both.
Meanwhile on Arch I have version `10.0.1`.

The quick fix is to disable compounds.
`precice-config-visualizer precice-config.xml | sed 's/compound=True;//' | dot -Tpng `

You could implement this as a fallback in case the conversion fails.

**Comment by fsimonis** [comment]
Another alternative is to install the Debian package from the [official release](
https://gitlab.com/graphviz/graphviz/-/releases)

**Comment by MakisH** [comment]
> sed 's/compound=True;//'

This is good enough for now. Thanks!

**Comment by fsimonis** [comment]
Closing, as this is not in our hand
