### ISSUE TITLE
GUI feature could be optional

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#23]
The GUI is nice for exploration, but since it now requires several additional dependencies, it is more complicated to integrate it into the CI, and especially into pre-commit. It might also be discouraging for users to install it.

In most cases, the CLI is enough. It would be nice that the GUI is an optional feature, to provide a baseline that is still very easy to install.

**Comment by fsimonis** [comment]
Important to know: the GUI dependencies cannot be installed via pip. They rely on the system.

I would prefer to make the GUI opt-out though. The normal user shouldn't suffer from this.

**Comment by MakisH** [comment]
Sure, but we need some way to disable it.
It could even be two packages: `precice-config-visualizer` and `precice-config-visualizer-gui`, with the latter depending on the former.

**Comment by fsimonis** [comment]
Yet another deep-dive thanks to incomplete documentation...

The entry-point specification allows adding an "extra" it depends on, but this is essentially deprecated, and unsupported in virtually every package handler.

One solution is to split up packages if they require an entry point depending on an extra. Then there can be an optional dependency in the base package that installs the gui like so:

```
[project.optional-dependencies]
gui = [ "precice-config-visualizer-gui" ]
```

So, yes, we would have to split up the package, leading to two repos with independent versioning, yet tight integration. To make this usable, we would have to redesign the interface of the actual implementation, as we are currently passing namespaces around.

I really wonder if this pain is worth it. We can always install the necessary things in the CI.

**Comment by MakisH** [comment]
Do we really need to have two repositories? Can't we have two directories? I can imagine this is not the first project with this problem, and I hope people don't split up large repositories just to provide two different packages on PIP.

**Comment by fsimonis** [comment]
Two packages in one repository is possible, but comes at the downside of a more complicated installation procedure when installing straight from the repo and having common versioning for both packages.

A valid, but error-prone possibly is to mark the gui components as optional and then check in the gui entry point if these dependencies have been installed.

Not pretty, but prevents splitting the package.

**Comment by MakisH** [comment]
> comes at the downside of a more complicated installation procedure when installing straight from the repo

I think only a couple of developers would ever do that, given that the packages will be on PyPI.

> having common versioning for both packages

Sounds like a feature to me.

> A valid, but error-prone possibly is to mark the gui components as optional and then check in the gui entry point if these dependencies have been installed.

That would be my naive approach, not sure how error-prone that would be. I guess we can just try it?

**Comment by fsimonis** [comment]
After some thought, splitting up the package definitely is the cleanest solution.
Independent versioning also prevents unnecessary clutter in the repo.

Common versioning sounds good at first, but we autodetect the version from the git tag. I cannot find a way to inject this version to sync the dependencies between the two packages.

> That would be my naive approach, not sure how error-prone that would be. I guess we can just try it?

The problem is, that this makes the GUI defunct by default. In addition, `.desktop` integration doesn't have terminal output, so the GUI will silently fail (by default). Not very user-friendly.

Concrete steps:
1. Refactor the interface of `common.py`.
2. Create a `config-visualizer-gui` repo and copy the GUI implementation over.
3. Remove the GUI from the config-visualizer (good candidate for release `1.0.0`)
4. Check if the packages can co-exist properly.
5. publish GUI on PyPi
6. documentation. :tada:

**Comment by MakisH** [comment]
But then this sounds like too much work, that should not block us in this release cycle.

**Comment by fsimonis** [comment]
It's more work than it sounds like. I can do that today.

**Comment by fsimonis** [comment]
Done

I moved the GUI components into a separate package over at https://github.com/precice/config-visualizer-gui and it is on PyPi https://pypi.org/project/precice-config-visualizer-gui

`config-visualizer` releases of note:
* 0.3.0 refactors the interface functions
* 1.0.0 removes the GUI (breaking change -> major version)
* 1.1.0 adds the GUI as an optional dependency for the gui extra. Meaning you can install it with `precice-config-visualizer[gui]`.
