### ISSUE TITLE
Direction of arrows for watchpoints

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#28]
Watchpoints are currently visualized with an arrow pointing to the participant:

![precice-config](https://github.com/user-attachments/assets/52c8a29c-7cc0-4d7e-b3a5-bacb641c8393)

As pointed by a user at the preCICE Workshop 2024, these are actually outputs, so it would make more sense that they have the reverse order.

**Comment by fsimonis** [comment]
In addition to that, the watchpoints should really originate from the mesh, not the participant.

Example

![image](https://github.com/user-attachments/assets/a49c6353-a37f-407b-be2d-c727f8cbcff6)

**Comment by fsimonis** [comment]
Fixed in https://github.com/precice/config-visualizer/commit/266d29b7f489ab20e7607db076f556845dc36dc8
