### ISSUE TITLE
Creating graph fails with syntax error

### ISSUE THREAD

**Issue by ajaust** [precice/config-visualizer#5]
I cannot create the graph using dot in the newest version e3723d8e122ed77f16f0e9209aa5e65aca32532c of the script.

I am on Ubuntu 18.04 LTS.

For the attached config file I get a syntax error near line 21. 
```
$ cat precice-config.xml | precice-config-visualizer | dot -Tpdf > config.pdf
Error: <stdin>: syntax error in line 21 near '['
```
The line looks like 
```
"HDFlowSolver" [color=['#0173B2', '#DE8F05', '#029E73', '#D55E00', '#CC78BC', '#CA9161', '#FBAFE4', '#949494', '#ECE133', '#56B4E9'], shape=doubleoctagon];
```
In the previous version 0717e507c579e067139a54223f903cfa9332cd74 the line looked like 
```
"HDFlowSolver" [color="#0173b2", shape=doubleoctagon];
```

I have attached the `precice-config.xml` as well as the output created for the current commit and the output for the previous commit.

**Attached files**

[precice-config.xml.txt](https://github.com/precice/config-visualizer/files/5243906/precice-config.xml.txt)
[vis_new.viz.txt](https://github.com/precice/config-visualizer/files/5243926/vis_new.viz.txt)
[vis_old.viz.txt](https://github.com/precice/config-visualizer/files/5243927/vis_old.viz.txt)

**Comment by fsimonis** [comment]
Thanks for the report!
Fixed in d8f79b6
