### ISSUE TITLE
Cannot process XML files formatted with our formatter

### ISSUE THREAD

**Issue by MakisH** [precice/config-visualizer#6]
Currently, the config-visualizer always fails if the XML file specifies the encoding: `<?xml version="1.0" encoding="UTF-8" ?>`.

However, our XML formatter adds the encoding (which I guess is a good practice). This means that we (or more importantly, our users) are not able to use the config-visualizer with the configuration files we give them out-of-the-box.

Simply removing the `encoding="UTF-8"` works, but we need to fix it in the tool.

**Comment by fsimonis** [comment]
The input file is read as a bytestream and then passed to the parser:
 
https://github.com/precice/config-visualizer/blob/79d7c1c3f04bf1f23b2ea463eb7d1445ab720afc/bin/precice-config-visualizer#L224

https://github.com/precice/config-visualizer/blob/79d7c1c3f04bf1f23b2ea463eb7d1445ab720afc/bin/precice-config-visualizer#L230

The parser then decides on the encoding given the encoding tag `<?xml version="1.0" encoding="UTF-8" ?>` here:

https://github.com/precice/config-visualizer/blob/79d7c1c3f04bf1f23b2ea463eb7d1445ab720afc/bin/precice-config-visualizer#L21-L23

Maybe we use the parser incorrectly?

**Comment by fsimonis** [comment]
What we really need are some basic tests based on some real examples.
This requires restructuring the repo, which I started in this https://github.com/precice/config-visualizer/tree/no-bin
